import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css' // Keep this import for global styles

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ja'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <footer className='flex items-center justify-center h-16 border-t'>
          <p className='text-sm text-gray-500'>
            Powered by{' '}
            <a
              href='https://pokohanada.com'
              target='_blank'
              rel='noopener noreferrer'
              className='text-blue-500 hover:underline'
            >
              PokoHanada.com
            </a>
          </p>
        </footer>
      </body>
    </html>
  )
}
